import { chromium } from "playwright";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";
const __dirname = dirname(fileURLToPath(import.meta.url));
const API="http://localhost:19653", BASE="http://localhost:3000";
const uniq=String(process.hrtime.bigint()).slice(-9);
const r=await fetch(API+"/api/auth/register",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({firstName:"ליאור",lastName:"מדן",username:`lior_${uniq}`,email:`lior_${uniq}@k.local`,password:"Passw0rd!23",role:1})});
const s=(await r.json()).data;
const authUser={id:s.user.userId,name:s.user.fullName,email:s.user.email,avatar:"",role:"participant",canCreateProjects:true,canJoinProjects:true,isProfileComplete:true,emailVerified:true};
const seed=JSON.stringify({state:{token:s.accessToken,refreshToken:s.refreshToken,user:authUser,isAuthenticated:true},version:0});
const b=await chromium.launch();
const ctx=await b.newContext({locale:"he-IL",viewport:{width:1280,height:800}});
await ctx.addInitScript((v)=>{try{sessionStorage.setItem("kibbutz-auth",v)}catch{}},seed);
await ctx.addCookies([{name:"kibbutz-session",value:"1",url:BASE},{name:"kibbutz-role",value:"participant",url:BASE}]);
const p=await ctx.newPage();
const errs=[];p.on("pageerror",e=>errs.push("PE:"+e.message.slice(0,140)));p.on("console",m=>{if(m.type()==="error")errs.push(m.text().slice(0,140))});
await p.goto(BASE+"/projects",{waitUntil:"load"});await p.waitForTimeout(1800);
console.log("url=",p.url().replace(BASE,""),"errs=",errs.length,errs.slice(0,2));
await p.screenshot({path:join(__dirname,"clean-home.png")});
await b.close();console.log("done");
